import re

def str2emoji(text):
    text = re.sub(r":‑\)"," ☺️ ",text)
    text = re.sub(r":\)\)\)\)"," ☺️ ",text)
    text = re.sub(r":\)\)\)"," ☺️ ",text)
    text = re.sub(r":\)\)"," ☺️ ",text)
    text = re.sub(r":\)"," ☺️ ",text)
    text = re.sub(r":-\]"," ☺️ ",text)
    text = re.sub(r":\]"," ☺️ ",text)
    text = re.sub(r":-3"," ☺️ ",text)
    text = re.sub(r":3","  ☺️ ",text)
    text = re.sub(r":->"," ☺️ ",text)
    text = re.sub(r"</3",' 💔 ',text)
    text = re.sub(r"<3"," ❤️ ",text)
    text = re.sub(r":>"," ☺️ ",text)
    text = re.sub(r"8-\)"," ☺️ ",text)
    text = re.sub(r":o\)"," ☺️ ",text)
    text = re.sub(r":-\}"," ☺️ ",text)
    text = re.sub(r":\}"," ☺️ ",text)
    text = re.sub(r":-\)"," ☺️ ",text)
    text = re.sub(r":c\)"," ☺️ ",text)
    text = re.sub(r":\^\)"," ☺️ ",text)
    text = re.sub(r"=\]"," ☺️ ",text)
    text = re.sub(r"=\)"," ☺️ ",text)
    text = re.sub(r":‑D"," 😃 ",text)
    text = re.sub(r":D"," 😃 ",text)
    text = re.sub(r"8‑D"," 😃 ",text)
    text = re.sub(r"8D"," 😃 ",text)
    text = re.sub(r"X‑D"," 😃 ",text)
    text = re.sub(r"XD"," 😃 ",text)
    text = re.sub(r"=D"," 😃 ",text)
    text = re.sub(r"=3"," 😃 ",text)
    text = re.sub(r"B\^D"," 😃 ",text)
    text = re.sub(r":-\)\)"," 😃 ",text)
    text = re.sub(r":‑\("," ☹️ ",text)
    text = re.sub(r":-\("," ☹️ ",text)
    text = re.sub(r":-d", " 🤤 ",text)
    text = re.sub(r":d", " 🤤 ",text)
    text = re.sub(r"=d", " 🤤 ",text)

    text = re.sub(r":\("," ☹️ ",text)
    text = re.sub(r":‑c"," ☹️ ",text)
    text = re.sub(r":c"," ☹️ ",text)
    text = re.sub(r":‑<"," ☹️ ",text)
    text = re.sub(r":<"," ☹️ ",text)
    text = re.sub(r":‑\["," ☹️ ",text)
    text = re.sub(r":\["," ☹️ ",text)
    text = re.sub(r":-\|\|"," ☹️ ",text)
    text = re.sub(r">:\["," ☹️ ",text)
    text = re.sub(r":\{"," ☹️ ",text)
    text = re.sub(r":@"," ☹️ ",text)
    text = re.sub(r">:\("," ☹️ ",text)
    text = re.sub(r":'‑\("," 😭 ",text)
    text = re.sub(r":'\("," 😭 ",text)
    text = re.sub(r":'‑\)"," 😃 ",text)
    text = re.sub(r":'\)"," 😃 ",text)
    text = re.sub(r"D‑':"," 😧 ",text)
    text = re.sub(r"D:<"," 😨 ",text)
    text = re.sub(r"D:"," 😧 ",text)
    text = re.sub(r"D8"," 😧 ",text)
    text = re.sub(r"D;"," 😧 ",text)
    text = re.sub(r"D="," 😧 ",text)
    text = re.sub(r"DX"," 😧 ",text)
    text = re.sub(r":‑O"," 😮 ",text)
    text = re.sub(r":O"," 😮 ",text)
    text = re.sub(r":‑o"," 😮 ",text)
    text = re.sub(r":o"," 😮 ",text)
    text = re.sub(r":-0"," 😮 ",text)
    text = re.sub(r"8‑0"," 😮 ",text)
    text = re.sub(r">:O"," 😮 ",text)
    text = re.sub(r":-\*"," 😗 ",text)
    text = re.sub(r":\*"," 😗 ",text)
    text = re.sub(r":X"," 😗 ",text)
    text = re.sub(r";‑\)"," 😉 ",text)
    text = re.sub(r";\)"," 😉 ",text)
    text = re.sub(r"\*-\)"," 😉 ",text)
    text = re.sub(r"\*\)"," 😉 ",text)
    text = re.sub(r";‑\]"," 😉 ",text)
    text = re.sub(r";\]"," 😉 ",text)
    text = re.sub(r";\^\)"," 😉 ",text)
    text = re.sub(r":‑,"," 😉 ",text)
    text = re.sub(r";D"," 😉 ",text)
    text = re.sub(r":‑P"," 😛 ",text)
    text = re.sub(r":‑p"," 😛 ",text)
    text = re.sub(r":P"," 😛 ",text)
    text = re.sub(r":p"," 😛 ",text)
    text = re.sub(r"X‑P"," 😛 ",text)
    text = re.sub(r"XP"," 😛 ",text)
    text = re.sub(r"xp"," 😛 ",text)
    text = re.sub(r":‑Þ"," 😛 ",text)
    text = re.sub(r":Þ"," 😛 ",text)
    text = re.sub(r":b"," 😛 ",text)
    text = re.sub(r"d:"," 😛 ",text)
    text = re.sub(r"=p"," 😛 ",text)
    text = re.sub(r">:P"," 😛 ",text)
    text = re.sub(r":‑/"," 😕 ",text)
    text = re.sub(r":/"," 😕 ",text)
    text = re.sub(r":-\[\.\]"," 😕 ",text)
    text = re.sub(r">:/"," 😕 ",text)
    text = re.sub(r"=/"," 😕 ",text)
    text = re.sub(r":L"," 😕 ",text)
    text = re.sub(r"=L"," 😕 ",text)
    text = re.sub(r":S"," 😕 ",text)
    text = re.sub(r":‑\|"," 😐 ",text)
    text = re.sub(r":\|"," 😐 ",text)
    text = re.sub(r":$"," 😳 ",text)
    text = re.sub(r":‑x"," 🤐 ",text)
    text = re.sub(r":x"," 🤐 ",text)
    text = re.sub(r":‑#"," 🤐 ",text)
    text = re.sub(r":#"," 🤐 ",text)
    text = re.sub(r":‑&"," 🤐 ",text)
    text = re.sub(r":&"," 🤐 ",text)
    text = re.sub(r"O:‑\)"," 😇 ",text)
    text = re.sub(r"O:\)"," 😇 ",text)
    text = re.sub(r"0:‑3"," 😇 ",text)
    text = re.sub(r"0:3"," 😇 ",text)
    text = re.sub(r"0:‑\)"," 😇 ",text)
    text = re.sub(r"0:\)"," 😇 ",text)
    text = re.sub(r":‑b"," 😛 ",text)
    text = re.sub(r"0;\^\)"," 😇 ",text)
    text = re.sub(r">:‑\)"," 😈 ",text)
    text = re.sub(r">:\)"," 😈 ",text)
    text = re.sub(r"\}:‑\)"," 😈 ",text)
    text = re.sub(r"\}:\)"," 😈 ",text)
    text = re.sub(r"3:‑\)"," 😈 ",text)
    text = re.sub(r"3:\)"," 😈 ",text)
    text = re.sub(r">;\)"," 😈 ",text)
    text = re.sub(r"\|;‑\)"," 😎 ",text)
    text = re.sub(r"\|‑O"," 😏 ",text)
    text = re.sub(r":‑J"," 😏 ",text)
    text = re.sub(r"%‑\)"," 😵 ",text)
    text = re.sub(r"%\)"," 😵 ",text)
    text = re.sub(r":-###.."," 🤒 ",text)
    text = re.sub(r":###.."," 🤒 ",text)
    text = re.sub(r"\(>_<\)"," 😣 ",text)
    text = re.sub(r"\(>_<\)>"," 😣 ",text)
    text = re.sub(r"\(';'\)"," 👶 ",text)
    text = re.sub(r"\(\^\^>``"," 😓 ",text)
    text = re.sub(r"\(\^_\^;\)"," 😓 ",text)
    text = re.sub(r"\(-_-;\)"," 😓 ",text)
    text = re.sub(r"\(~_~;\) \(・\.・;\)"," 😓 ",text)
    text = re.sub(r"\(-_-\)zzz"," 😴 ",text)
    text = re.sub(r"\(\^_-\)"," 😉 ",text)
    text = re.sub(r"\(\(\+_\+\)\)"," 😕 ",text)
    text = re.sub(r"\(\+o\+\)"," 😕 ",text)
    text = re.sub(r"\^_\^"," 😃 ",text)
    text = re.sub(r"\(\^_\^\)/"," 😃 ",text)
    text = re.sub(r"\(\^O\^\)／"," 😃 ",text)
    text = re.sub(r"\(\^o\^\)／"," 😃 ",text)
    text = re.sub(r"\(__\)"," 🙇 ",text)
    text = re.sub(r"_\(\._\.\)_"," 🙇 ",text)
    text = re.sub(r"<\(_ _\)>"," 🙇 ",text)
    text = re.sub(r"<m\(__\)m>"," 🙇 ",text)
    text = re.sub(r"m\(__\)m"," 🙇 ",text)
    text = re.sub(r"m\(_ _\)m"," 🙇 ",text)
    text = re.sub(r"\('_'\)"," 😭 ",text)
    text = re.sub(r"\(/_;\)"," 😭 ",text)
    text = re.sub(r"\(T_T\) \(;_;\)"," 😭 ",text)
    text = re.sub(r"\(;_;"," 😭 ",text)
    text = re.sub(r"\(;_:\)"," 😭 ",text)
    text = re.sub(r"\(;O;\)"," 😭 ",text)
    text = re.sub(r"\(:_;\)"," 😭 ",text)
    text = re.sub(r"\(ToT\)"," 😭 ",text)
    text = re.sub(r";_;"," 😭 ",text)
    text = re.sub(r";-;"," 😭 ",text)
    text = re.sub(r";n;"," 😭 ",text)
    text = re.sub(r";;"," 😭 ",text)
    text = re.sub(r"Q\.Q"," 😭 ",text)
    text = re.sub(r"T\.T"," 😭 ",text)
    text = re.sub(r"QQ"," 😭 ",text)
    text = re.sub(r"Q_Q"," 😭 ",text)
    text = re.sub(r"\(-\.-\)"," 😞 ",text)
    text = re.sub(r"\(-_-\)"," 😞 ",text)
    text = re.sub(r"\(一一\)"," 😞 ",text)
    text = re.sub(r"\(；一_一\)"," 😞 ",text)
    text = re.sub(r"\(=_=\)"," 😩 ",text)
    text = re.sub(r"\(=\^\·\^=\)"," 😺 ",text)
    text = re.sub(r"\(=\^\·\·\^=\)"," 😺 ",text)
    text = re.sub(r"=_\^= "," 😺 ",text)
    text = re.sub(r"\(\.\.\)"," 😔 ",text)
    text = re.sub(r"\(\._\.\)"," 😔 ",text)
    text = re.sub(r"\(\・\・\?"," 😕 ",text)
    text = re.sub(r"\(\?_\?\)"," 😕 ",text)
    text = re.sub(r">\^_\^<"," 😃 ",text)
    text = re.sub(r"<\^!\^>"," 😃 ",text)
    text = re.sub(r"\^/\^"," 😃 ",text)
    text = re.sub(r"\（\*\^_\^\*）"," 😃 ",text)
    text = re.sub(r"\(\^<\^\) \(\^\.\^\)"," 😃 ",text)
    text = re.sub(r"\(^\^\)"," 😃 ",text)
    text = re.sub(r"\(\^\.\^\)"," 😃 ",text)
    text = re.sub(r"\(\^_\^\.\)"," 😃 ",text)
    text = re.sub(r"\(\^_\^\)"," 😃 ",text)
    text = re.sub(r"\(\^\^\)"," 😃 ",text)
    text = re.sub(r"\(\^J\^\)"," 😃 ",text)
    text = re.sub(r"\(\*\^\.\^\*\)"," 😃 ",text)
    text = re.sub(r"\(\^—\^\）"," 😃 ",text)
    text = re.sub(r"\(#\^\.\^#\)"," 😃 ",text)
    text = re.sub(r"\（\^—\^\）"," 👋 ",text)
    text = re.sub(r"\(;_;\)/~~~"," 👋 ",text)
    text = re.sub(r"\(\^\.\^\)/~~~"," 👋 ",text)
    text = re.sub(r"\(T_T\)/~~~"," 👋 ",text)
    text = re.sub(r"\(ToT\)/~~~"," 👋 ",text)
    text = re.sub(r"\(\*\^0\^\*\)"," 😍 ",text)
    text = re.sub(r"\(\*_\*\)"," 😍 ",text)
    text = re.sub(r"\(\*_\*;"," 😍 ",text)
    text = re.sub(r"\(\+_\+\) \(@_@\)"," 😍 ",text)
    text = re.sub(r"\(\*\^\^\)v"," 😂 ",text)
    text = re.sub(r"\(\^_\^\)v"," 😂 ",text)
    text = re.sub(r"\(ーー;\)"," 😓 ",text)
    text = re.sub(r"\(\^0_0\^\)"," 😎 ",text)
    text = re.sub(r"\(\＾ｖ\＾\)"," 😀 ",text)
    text = re.sub(r"\(\＾ｕ\＾\)"," 😀 ",text)
    text = re.sub(r"\(\^\)o\(\^\)"," 😀 ",text)
    text = re.sub(r"\(\^O\^\)"," 😀 ",text)
    text = re.sub(r"\(\^o\^\)"," 😀 ",text)
    text = re.sub(r"\)\^o\^\("," 😀 ",text)
    text = re.sub(r":O o_O"," 😮 ",text)
    text = re.sub(r"o_0"," 😮 ",text)
    text = re.sub(r"o\.O"," 😮 ",text)
    text = re.sub(r"\(o\.o\)"," 😮 ",text)
    text = re.sub(r"oO"," 😮 ",text)
    text = re.sub(r':\‑\)','😃',text)
    text = re.sub(r":\)"," ☺️ ",text)
    text = re.sub(r":-]"," ☺️ ",text)
    text = re.sub(r":]"," ☺️ ",text)
    text = re.sub(r"8\-\)"," ☺️ ",text)
    text = re.sub(r":o\)"," ☺️ ",text)
    text = re.sub(r":-}"," ☺️ ",text)
    text = re.sub(r":}"," ☺️ ",text)
    text = re.sub(r":\-\)"," ☺️ ",text)
    text = re.sub(r":c\)"," ☺️ ",text)
    text = re.sub(r":^\)"," ☺️ ",text)
    text = re.sub(r"=]"," ☺️ ",text)
    text = re.sub(r"=\)"," ☺️ ",text)
    text = re.sub(r"B^D"," 😃 ",text)
    text = re.sub(r":-\)\)"," 😃 ",text)
    text = re.sub(r":-\("," ☹️ ",text)

    text = re.sub(r":‑\("," ☹️ ",text)
    text = re.sub(r":\("," ☹️ ",text)
    text = re.sub(r":\‑\["," ☹️ ",text)
    text = re.sub(r":\["," ☹️ ",text)
    text = re.sub(r":-\|\|"," ☹️ ",text)
    text = re.sub(r">\:\["," ☹️ ",text)
    text = re.sub(r":{"," ☹️ ",text)
    text = re.sub(r">\:\("," ☹️ ",text)
    text = re.sub(r":'‑\("," 😭 ",text)
    text = re.sub(r":'\("," 😭 ",text)
    text = re.sub(r":'\‑\)"," 😃 ",text)
    text = re.sub(r":'\)"," 😃 ",text)
    text = re.sub(r":-\*"," 😗 ",text)
    text = re.sub(r":\*"," 😗 ",text)
    text = re.sub(r";\‑\)"," 😉 ",text)
    text = re.sub(r";\)"," 😉 ",text)
    text = re.sub(r"\*\-\)"," 😉 ",text)
    text = re.sub(r"\*\)"," 😉 ",text)
    text = re.sub(r";‑\]"," 😉 ",text)
    text = re.sub(r";\]"," 😉 ",text)
    text = re.sub(r";^\)"," 😉 ",text)
    text = re.sub(r">\:\[\(\)\]"," 😕 ",text)

    text = re.sub(r":\[\(\)\]"," 😕 ",text)
    text = re.sub(r"=\[\(\)\]"," 😕 ",text)
    text = re.sub(r":‑\|"," 😐 ",text)
    text = re.sub(r":\|"," 😐 ",text)
    text = re.sub(r"O:‑\)"," 😇 ",text)
    text = re.sub(r"O:\)"," 😇 ",text)
    text = re.sub(r"0:‑\)"," 😇 ",text)
    text = re.sub(r"0:\)"," 😇 ",text)
    text = re.sub(r"0;^\)"," 😇 ",text)
    text = re.sub(r">:‑\)"," 😈 ",text)
    text = re.sub(r">:\)"," 😈 ",text)
    text = re.sub(r"}:‑\)"," 😈 ",text)
    text = re.sub(r"}:\)"," 😈 ",text)
    text = re.sub(r"3:‑\)"," 😈 ",text)
    text = re.sub(r"3:\)"," 😈 ",text)
    text = re.sub(r">;\)"," 😈 ",text)
    text = re.sub(r"\|;‑\)"," 😎 ",text)
    text = re.sub(r"\|‑O"," 😏 ",text)
    text = re.sub(r"%‑\)"," 😵 ",text)
    text = re.sub(r"%\)"," 😵 ",text)
    text = re.sub(r"\(>_<\)"," 😣 ",text)
    text = re.sub(r"\(>_<\)>"," 😣 ",text)
    text = re.sub(r"\(';'\)"," Baby ",text)
    text = re.sub(r"\(^^>``"," 😓 ",text)
    text = re.sub(r"\(^_^;\)"," 😓 ",text)
    text = re.sub(r"\(-_-;\)"," 😓 ",text)

    text = re.sub(r"\(~_~;\) \(・\.・;\)"," 😓 ",text)
    text = re.sub(r"\(-_-\)zzz"," 😴 ",text)
    text = re.sub(r"\(^_-\)"," 😉 ",text)
    text = re.sub(r"\(\(\+_\+\)\)"," 😕 ",text)
    text = re.sub(r"\(\+o\+\)"," 😕 ",text)
    text = re.sub(r"^_^"," 😃 ",text)
    text = re.sub(r"\(^_^\)/"," 😃 ",text)
    text = re.sub(r"\(^O^\)／"," 😃 ",text)
    text = re.sub(r"\(__\)"," 🙇 ",text)
    text = re.sub(r"_\(._.\)_"," 🙇 ",text)
    text = re.sub(r"<\(_ _\)>"," 🙇 ",text)
    text = re.sub(r"<m\(__\)m>"," 🙇 ",text)
    text = re.sub(r"m\(__\)m"," 🙇 ",text)
    text = re.sub(r"m\(_ _\)m"," 🙇 ",text)
    text = re.sub(r"\('_'\)"," 😭 ",text)
    text = re.sub(r"\(/_;\)"," 😭 ",text)
    text = re.sub(r"\(T_T\) (;_;)"," 😭 ",text)
    text = re.sub(r"\(;_;"," 😭 ",text)
    text = re.sub(r"\(;_:\)"," 😭 ",text)
    text = re.sub(r"\(;O;\)"," 😭 ",text)
    text = re.sub(r"\(:_;\)"," 😭 ",text)
    text = re.sub(r"\(ToT\)","  😭  ",text)
    text = re.sub(r"Q\.Q"," 😭 ",text)
    text = re.sub(r"T\.T"," 😭 ",text)
    text = re.sub(r"\(-\.-\)"," 😞 ",text)
    text = re.sub(r"\(-_-\)"," 😞 ",text)

    text = re.sub(r"\(一一\)"," 😞 ",text)
    text = re.sub(r"\(；一_一\)"," 😞 ",text)

    text = re.sub(r"\(=\_=\)"," 😩 ",text)
    text = re.sub(r"\(=^\·^=\)"," 😺 ",text)

    text = re.sub(r"\(=^··^=\)"," 😺 ",text)
    text = re.sub(r"=_^= "," 😺 ",text)

    text = re.sub(r"\(\.\.\)"," 😔 ",text)

    text = re.sub(r"\(\._\.\)"," 😔  ",text)
    text = re.sub(r"\(・・\?"," 😕 ",text)
    text = re.sub(r"\(\?_\?\)"," 😕 ",text)

    text = re.sub(r">^_^<"," 😃 ",text)
    text = re.sub(r"<^\!^>"," 😃 ",text)
    text = re.sub(r"^/^","  😃  ",text)
    text = re.sub(r"\(\*^_^\*\)","  😃  ",text)
    text = re.sub(r"\(^^\)","  😃  ",text)
    text = re.sub(r"\(^\.^\)","  😃  ",text)
    text = re.sub(r"\(^_^\.\)","  😃  ",text)
    text = re.sub(r"\(^_^\)","  😃  ",text)
    text = re.sub(r"\(^J^\)","  😃  ",text)
    text = re.sub(r"\(\*^\.^\*\)"," 😃  ",text)
    text = re.sub(r"\(^—^\）"," 😃 ",text)

    text = re.sub(r"\(#^.^#\)"," 😃 ",text)
    text = re.sub(r"\(^—^\)"," 👋 ",text)
    text = re.sub(r"\(;_;\)/~~~","  👋  ",text)

    text = re.sub(r"\(^.^\)/~~~"," 👋 ",text)
    text = re.sub(r"\(-_-\)/~~~ \($··\)/~~~"," 👋 ",text)
    text = re.sub(r"\(T_T\)/~~~"," 👋 ",text)

    text = re.sub(r"\(ToT\)/~~~"," 👋 ",text)
    text = re.sub(r"\(\*^0^\*\)"," 😍 ",text)
    text = re.sub(r"\(\*_\*\)"," 😍 ",text)

    text = re.sub(r"\(\*_\*;"," 😍 ",text)
    text = re.sub(r"\(+_+\) \(@_@\)"," 😍 ",text)
    text = re.sub(r"o\.O"," 😮 ",text)
    text = re.sub(r"\(o\.o\)"," 😮 ",text)

    return text